### ISSUE TITLE
Falling through terrain

### ISSUE THREAD

**Issue by ggreer91** [Ethanol10/Ror2Ganon#3]
When you use Flame Choke on a Wandering Vagrant, there's a chance you'll fall through terrain while still holding onto the enemy, flying around uncontrollably and taking damage over time (not sure why I was taking damage over time, might be because I was out of bounds?). Thought I'd let you know about it!

**Comment by Ethanol10** [comment]
Hi there,

Thanks for the report, yeah I've encountered that many times, the last time I tried I was not able to fix it sadly. I'm not sure if I have time to fix it, but when I do I'll try do what I can. 

Regards, 
Ethan
