### ISSUE TITLE
Want to change cooldowns

### ISSUE THREAD

**Issue by lowfatlatte0** [Ethanol10/Ror2Ganon#4]
The character seems quite strong compared to the original cast. My friends and I after some playtesting simply believe  his cooldowns on his secondary and utility are  potentially too low. Is there any way you could make a setting for the cooldowns in the config?  I think you have done a great job by the way and his gameplay feels amazing.

**Comment by Ethanol10** [comment]
Hi there, 

Yeah I can add them, though with every change you will need to restart ror2, is that ok?

**Comment by lowfatlatte0** [comment]
100% cool :). I will change the numbers through modman before I launch.

**Comment by lowfatlatte0** [comment]
fine by me :).

**Comment by Ethanol10** [comment]
Added a config in the latest release, please have a look! 

Closing this issue now.
