### ISSUE TITLE
Ganondorf Health gain is extremely low for a melee character.

### ISSUE THREAD

**Issue by Ninjaraisen** [Ethanol10/Ror2Ganon#6]
Ganondorf gains 15 health per level, which is very low compared to other chars. I know he starts with like 250 health, but he gets outscaled pretty easily by every other character in health. Could you please increase this to at least 30, maybe even 40 since hes a melee character with no sustain? (sustain being healing or barrier for when he is in combat.)

**Comment by Ninjaraisen** [comment]
Just to give you an idea, most survivors have 33 health gain per level. Bulky characters like Loader and Acrid have 48, and MULT is exceptional with about 60, but he has no mobility.

The lowest health gain per level that I can find is Huntress with 27 per level. I was shocked when mid game I asked how much health my friend had playing huntress on stage 3, and it was the same as mine. So yeah, 15 health gain is pretty bad for a melee character. :C

**Comment by Ethanol10** [comment]
Yeah I'll buff it when I get time.

**Comment by Ethanol10** [comment]
Should be buffed now.
